### ISSUE TITLE
tmsu: could not query files: near "RECURSIVE": syntax error

### ISSUE THREAD

**Issue by SignMyPublicKey** [oniony/TMSU#103]
I keep getting this error when searching for files:
```
me@mercurius:~$ tmsu tag test.py code
tmsu: new tag 'code'
me@mercurius:~$ tmsu files code
tmsu: could not query files: near "RECURSIVE": syntax error
```
The strange thing is, that getting all tags and all files does work, just not the tagging itself:
```
me@mercurius:~$ tmsu tags
code
me@mercurius:~$ tmsu files
./test.py
```

System details:
Ubuntu 14.04
Installed tmsu using the amd64.deb as recommended by the ppa description [here](https://launchpad.net/%7Etmsu/+archive/ubuntu/ppa)
Updated SQLite3 to 3.8.2 as it was recommended in issue #44.

Is there something more I need do update/upgrade or is it impossible to get tmsu to work in Ubuntu 14.04? Which would make me kind of sad, I really like the project.

**Comment by oniony** [comment]
Hmm, sounds like the version of Sqlite3 you have does not support the `RECURSIVE` keyword. That would suggest that your upgrade has not been entirely successful: could you please run `sqlite3 --version` and see what you get?

**Comment by oniony** [comment]
Actually, looks like `RECURSIVE` was added in Sqlite3 [version 3.8.3](http://stackoverflow.com/questions/7456957/basic-recursive-query-on-sqlite3#7457134).

**Comment by oniony** [comment]
Cool, no problem. According to [DistroWatch](http://distrowatch.com/table.php?distribution=ubuntu) it looks like you're quite some behind (press the Refresh button above the table to see all packages including Sqlite3).

**Comment by oniony** [comment]
Added this issue to the [Troubleshooting](https://github.com/oniony/TMSU/wiki/Troubleshooting) page.

**Comment by SignMyPublicKey** [comment]
Check, this solved the problem! Thanks for your help!

**Comment by oniony** [comment]
Cool, glad you got it working. Give us a shout if you have any other problems.
