### ISSUE TITLE
`tmsu mv` command for moving files while retaining tags

### ISSUE THREAD

**Issue by tmladek** [oniony/TMSU#11]
Since tmsu doesn't explicitly monitor filesystem changes, it'd be nice if there were an analogue of `git mv` - a move command that also adds the move to the staging area - for tmsu, that would move the file while updating the database so that no tag info is lost.

**Comment by oniony** [comment]
OK, after looking at issue #20, I've decided I'll include a set of shell functions with TMSU. Currently I have:

* tmsu-rm
* tmsu-mv
* tmsu-mergefiles

This should allow users to do these operations simply without TMSU itself performing any changes to the managed files on disk.

I've created a new issue #35 for this.
