### ISSUE TITLE
'tmsu -D foo/some.db init' does not init foo/some.db

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#112]
Steps to reproduce
1. `alias tadmin="tmsu -D=$HOME/.tmsu/admin.db"`
2. `tadmin stats`  (message: "tmsu: no database found: use 'tmsu init' to create one")
3. `tadmin --verbose init` (message: "... creating database at '**/home/kau/.tmsu/db**' ")

Entering `tadmin init ~/.tmsu/admin.db` gives the error '.tmsu/admin.db: could not initialize database: database transaction error: unable to open database file'. Presumably, this is because it is interpreting admin.db as a directory name.

In my view, some way to initialize an exact db file is needed. Whether that is `tmsu -D=some/path/to/dbfile init` or something else.

Currently, it seems to be necessary to work around this behaviour by creating a database in /tmp/ and moving it to the desired location. (`cd /tmp/;tmsu init; mv .tmsu/db ~/.tmsu/admin.db`)

**Comment by oniony** [comment]
Hi, thanks for reporting this.

Yes, it does seem wrong. You should be able to specify a path to the database file as an argument. If the path already exists, and is a directory, then the database file should be created inside of it.

**Comment by oniony** [comment]
Just retested this and seems to work fine with the following syntax:

    $ tmsu init some/other/path
    tmsu: some/other/path: creating database
    $ cd some/other/path
    $ tmsu info
    Database: some/other/path/.tmsu/db
    Root path: some/other/path
    Size: 26624
