### ISSUE TITLE
Use relative symlinks in VFS

### ISSUE THREAD

**Issue by jrmrjnck** [oniony/TMSU#116]
I would like the option to have the VFS show relative symlinks, rather than absolute links. My particular use case involves exporting a directory full of files (and the tmsu mountpoint in a subdirectory) over SMB. On the client machine, the VFS symlinks are only valid as long as the directory is mounted at the exact same path as on the server machine. It would be nice to have the flexibility of mounting anywhere on the client.

**Comment by oniony** [comment]
Hi,

Sounds like a reasonable request. I'll have a think about it.

**Comment by DonRichie** [comment]
I can't read my files over samba, too.
I think due to the same reason. Add me to the list of people liking that enhancement request :)

**Comment by jrmrjnck** [comment]
Something changed in samba such that it no longer shows symlinks on the client side, but instead resolves the symlink so it looks like a normal file. I didn't change any configuration, but that's the behavior I wanted so this issue is no longer immediately relevant to me. I still think relative symlinks are a good idea, e.g. for other network mounts like sshfs.
