### ISSUE TITLE
Blake2 fingerprinting

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#117]
I've recently learnt about the hashing algorithm [Blake2(b/s)](https://blake2.net/). I believe this would be a good hash for TMSU to support, possibly even to use by default for new DBs. Mainly in consideration of these factors:

* Significantly faster than **all** hashing functions currently supported by TMSU. (aside from `none` ;)
* More secure than MD5 or SHA1 (probably also SHA256, this is a little less clear)
* Existing implementations for Go, Rust, and many other languages.
* System support (`b2sum` is in GNU Coreutils for example, and OpenSSL supports blake2 hashing)

Downsides:

* Digest size (512bit) may be unnecessarily large. I think this is tunable though.
* Additional code, obviously.

**Comment by oniony** [comment]
Thanks, I'd not heard of that. certainly does sound intriguing.

As for default, I've realised I can't change the true default as this would
lead to a mix of algorithms for people with existing databases who have not
set config. However, I could populate the algorithm to default it to Blake
for new databases.

**Comment by nsuper** [comment]
https://github.com/Cyan4973/xxHash Extremely fast non-cryptographic hash algorithm

"More secure than MD5..." for what?

**Comment by 0ion9** [comment]
Well, admittedly the security in this context mainly matters as a reasonable assurance that you won't have two files with the same hash (==wrongly detected as dupe), because there are no known attacks on Blake2.

The algo you link does look interesting, and in fact, generally quite preferable IMO. The only downside seems to be the lesser awareness/support (eg. no Go port yet).

**Comment by nsuper** [comment]
I'm using this package: https://github.com/cespare/xxhash a Go implementation of the 64-bit xxHash algorithm, XXH64. This is a high-quality hashing algorithm that is much faster than anything in the Go standard library.

**Comment by edmund-troche** [comment]
@0ion9 Blake2(b|s) is now in https://github.com/golang/crypto.

**Comment by foxcpp** [comment]
@oniony, you forgot to close this.

**Comment by oniony** [comment]
Ta
