### ISSUE TITLE
HTTPS support for TMSU homepage

### ISSUE THREAD

**Issue by fturco** [oniony/TMSU#118]
It seems tmsu.org doesn't support HTTPS yet. Let me suggest you [Let's Encrypt](https://letsencrypt.org/) free SSL certificates.

**Comment by oniony** [comment]
Cool, thanks. I was waiting for my host (nearlyfreespeech.net) to support HTTP/2, which is encrypted by default.

**Comment by oniony** [comment]
I checked the Nearlfreespeech.net forums and [it turned out](https://members.nearlyfreespeech.net/forums/viewtopic.php?t=9230&sid=ba9d596851ac6415b287ba3ca309c4be) they already had a script for using Let's Encrypt. So I've run it and it's now in operation.

Cheers.
