### ISSUE TITLE
Logo Redesign

### ISSUE THREAD

**Issue by TheChymera** [oniony/TMSU#120]
A somewhat less technical concern. Would you be interested in redesigning (or accepting a user-submitted redesign) of the TMSU logo? The color and shape make the "S" quite unpleasantly evocative.

If you have any specific wishes of a user-submitted design, I am sure I could integrate that.

**Comment by oniony** [comment]
The S is intentionally a turd. No, I'm not interested in a new logo, I like
this one.

Thanks though.
