### ISSUE TITLE
Filename and values are mixed in Virtual Filesystem

### ISSUE THREAD

**Issue by B-R-D** [oniony/TMSU#121]
Hi Paul,
I use TMSU to group my hunders of folders and I find an inconvinent issue.
My folders are tagged with the form of tag=value (e.g. author=someone). But when I use the Virtual Filesystem with `ls tags/author`, the values and files are mixed together and I can hardly find the "=someone" folder I want to find.
Is there any way to make the virtual filesystem only display the "=value" folders instead of the filenames with tag?

Best Regards

**Comment by oniony** [comment]
Hi,

Yes that unreleased version separates out the files. If you build from
source you can access this functionality earlier.

Paul

**Comment by xingxuanma** [comment]
Thank you, and when the next version will be released?

Best regards

**Comment by oniony** [comment]
I'm not 100% sure. There are a few issues I want to complete before I push 0.7.0 out. Nothing major but I struggle to find time. Easiest thing for now would be to build from source (it's not hard) to get the latest.

**Comment by xingxuanma** [comment]
Take it easy. I've build a pre version, that's useful for me. I'm looking
forward to your work.

Thank you

2017-05-21 8:07 GMT+09:00 Paul Ruane <notifications@github.com>:

**Comment by xingxuanma** [comment]
Hi Paul,
There is something important I want to ask you. If I have to reinstall the TMSU or upgrade TMSU to a newer version, such as 0.8.0 or 1.* in the future, can the database(.db file) be reused? I don't want to rebulid the database, that's too troublesome.

I have backuped my database to another place in case of my file system down. Is it meaningless?

Best Regards

**Comment by oniony** [comment]
I have always taken care to either preserve backwards compatibility or
alternatively provide upgrade scripts.

Backing up your database is also good sense.

Even if the format were to change, it you wanted to use a different
product, it would be trivial to get the trading information you have
created using the standard Sqlite tooling.
