### ISSUE TITLE
The purpose of values is not clear, or there's a bug in tag=value implications

### ISSUE THREAD

**Issue by arnoo** [oniony/TMSU#123]
Hi,

I'd like to create a hierarchy of location values. Either I don't get how values work,  which seems likely (I could not find much documentation about that), or there's a bug ?

```
$ tmsu init
$ tmsu imply 'location=Bordeaux' 'location=France'
$ tmsu imply 'location=Paris' 'location=France'

cannot add implication of 'location=Paris' to 'location=France': implication would create a cycle
```

**Comment by oniony** [comment]
Yes that does look like a bug. You should be able to add both of those.

**Comment by oniony** [comment]
Which version are you using?

**Comment by arnoo** [comment]
Sorry, I forgot to mention that. I'm using version 0.6.1

**Comment by arnoo** [comment]
For what it's worth, I can't reproduce it on master / 442862c2413d923cdfaa236e8f80c07ea8df900b

**Comment by oniony** [comment]
Confirmed works fine with HEAD.
