### ISSUE TITLE
How to ignore hidden files while tagging a directory recursively?

### ISSUE THREAD

**Issue by exaos** [oniony/TMSU#129]
I want to tag files in a directory recursively but excluding hidden files and directories (e.g., .git/, .cvs/, .projects, etc.). Maybe, I can use `find` and `-exec tmsu tag ...` to do this. But, how to use tmsu directly, e.g.,

    tmus tag --recursive --tags="my test" --exclude=".git/ .hg/" my-path/

**Comment by oniony** [comment]
Yes there's no built in functionality at present: perhaps an oversight. I think it should ignore these files by default and a flag be added to get them to be picked up.
