### ISSUE TITLE
Return file names in quotation marks

### ISSUE THREAD

**Issue by TheChymera** [oniony/TMSU#133]
`tmsu files "mytagA mytagB"` returns a list of files separated by newline characters. I'd like to pass it to e.g. `mpv`. currently the best I could do was:

```
tmsu files "mytagA mytagB" | xargs -0 echo > files
mpv --playlist=files
```

Any advice what I could do to resolve this on a single line (ideally with minimal scripting)?

**Comment by oniony** [comment]
Use the --print0 option.
