### ISSUE TITLE
Windows OS -- VFS Mount???

### ISSUE THREAD

**Issue by DaemonPhoenix42** [oniony/TMSU#137]
Sorry if this doesn't belong here or is already mentioned, i just couldn't find it --
Been looking for a system similar to this but how does the windows executable handle mounting?
all I can tell is you can tag but not output to a VFS Directory. I'm probably overlooking something.
I assume the mount command is Linux specific

For some context, I'v got a mass amount of sample libraries and want to tag specific entities and display them separate from the main file system because it would get pretty messy if I started modifying the way they are structured.

Someone help me get this to work how I want lol

**Comment by oniony** [comment]
Currently the virtual filesystem is not supported on Windows. It's on the roadmap but I've not had any time to work on TMSU of late so I'm not sure when it will happen.

**Comment by oniony** [comment]
Btw, please use the mailing list for questions.

**Comment by DaemonPhoenix42** [comment]
That's unfortunate, I'm unaware if there's a work around for the time being so I was gonna take a look. for example bash for windows or mounting a shared folder from a Linux VM system -- though the latter would be pretty resource heavy for such a simple task.

Can't wait for official support but I understand, Thank you for your reply.
- Have a great day
