### ISSUE TITLE
bug: “imply” disregards values

### ISSUE THREAD

**Issue by Fornost461** [oniony/TMSU#141]
### Steps to reproduce:

1. Tag a file with a tag and a value:
```
$ tmsu tag my_file tag1=value1
tmsu: new tag 'tag1'
tmsu: new value 'value1'
$ tmsu tags my_file
tag1=value1
```
2. Create an implication from the same tag and another value:
```
$ tmsu imply tag1=value2 tag2
tmsu: new value 'value2'
tmsu: new tag 'tag2'
```
3. Check the result:
```
$ tmsu files tag2
./my_file
$ tmsu tags my_file
tag1=value1
$ tmsu imply
tag1=value2 -> tag2
```
`my_file` should not appear with the query `tag2`, since `my_file` is neither tagged `tag2` nor `tag1=value2`.

This may be related to #123.

My version of tmsu is `0.7.0`.

**Comment by oniony** [comment]
OK, will look to fix for 0.7.1. Can't offer a time at present.

**Comment by Fornost461** [comment]
Take your time, your software is wonderful.

**Comment by oniony** [comment]
Should be fixed now. I've added a test to cover this gap too. Thanks for finding this.
