### ISSUE TITLE
Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by shakasan** [oniony/TMSU#142]
Is there a chance to see a package for Ubuntu 18.04 and other derivatives ? :wink: 

Thanks a lot

**Comment by oniony** [comment]
Hi, sorry for the delay in responding. I use Arch Linux exclusively and I'm not involved in any package creation, even for the Arch package.

Somebody got in touch ages ago regarding Debian packages but there were some license issues with upstream packages that stopped this happening. I actually got the upstream project to fix up their license but the Debian package never happened AFAIK. I don't know if Ubuntu uses Debian packages or not, but I thought I'd mention this anyway :/

**Comment by anishmittal2020** [comment]
Please provide for Ubuntu 18.04. I tried to install from the PPAQ mentioned, but I get this error

```
E: The repository 'http://ppa.launchpad.net/tmsu/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by oniony** [comment]
I do not have the time, energy or inclination to provide packages for x, y
or z distro. TMSU is fairly easy to install from source and there are full
instructions in the COMPILING.md file. Just download a zip of the latest
from GitHub (or clone the repo) and follow the instructions.
