### ISSUE TITLE
tmsu-fs-mv drops the fingerprint

### ISSUE THREAD

**Issue by c7nh7r** [oniony/TMSU#143]
`$ echo "1" > file && tmsu tag file 1`
`sqlite> select * from file;
1|.|file|4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865|2018-06-09 14:14:34.432437945+02:00|2|0`

`$ tmsu-fs-mv file newfile`
`sqlite> select * from file;
1|.|newfile||2018-06-09 14:14:34.432437945+02:00|2|0`

The only way I found to get it back was to call `tmsu repair -u` but I don't think for a mv a full fingerprint recalculation should be done.

**Comment by oniony** [comment]
Bizarre. Thanks for reporting, I shall try to take a look this evening.

**Comment by oniony** [comment]
Sorry for the delay.

I think this is an issue with the manual repairs (`repair --manual`). You can see the code at https://github.com/oniony/TMSU/blob/master/src/github.com/oniony/TMSU/cli/repair.go#L179. The fields are all preserved except for the fingerprint which is initialised to a zero value. I'll need to modify this to preserve the existing fingerprint.

**Comment by oniony** [comment]
I've modified the code to preserve the existing fingerprint in e4411fd. However, I guess it should really calculate the fingerprint of the file at the new location.

**Comment by oniony** [comment]
Recalculates the fingerprint now, if it can.
