### ISSUE TITLE
Script command for checking if a directory is initialized for TMSU

### ISSUE THREAD

**Issue by D-Vaillant** [oniony/TMSU#144]
I'd imagine this wouldn't be *that* hard to implement but I don't know Go at all. So this is a sort of "low-hanging fruit" feature request.

I've been wanting to implement a wrapper around TMSU's CLI for integration into a file manager, but I need to make sure I can easily check to see if the directory I'm looking at is set up for tags. Currently I've been using `tmsu status 2&> /dev/null` as a kludge. Something like `tmsu info -q` that suppresses the print output would accomplish this.

**Comment by oniony** [comment]
Hi, yes this would be really easy to add. I'll take a look.

**Comment by oniony** [comment]
Just started on this and, upon reflection, I really don't think it's worth adding. I think `tmsu info` already does what you want and you can just ditch the output, as you were doing with the `status` subcommand, i.e.:

    $ tmsu info 2&>/dev/null
    tmsu: no database found: use 'tmsu init' to create one
    [1] $

I think this is perfectly fine way to do it. `info` only writes three lines and is pretty cheap to invoke, certainly a lot cheaper than `status', which will examine the current status of pretty much everything.
