### ISSUE TITLE
Repair fails, mentioning a random other untagged file

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [oniony/TMSU#149]
I have tagged a few files:

```
test/foo/bar/1.txt
test/foo/bar/2.txt
```
etc.

I then moved those up a few directories so:

```
test/1.txt
test/2.txt
```

then in `test/`, I ran:

`tmsu repair .`

and the output is:

`tmsu: stat: test/random/other/untagged/file: no such file or directory`

That file is present, and it's untagged. Not sure why tmsu is mentioning that file and ignoring 1.txt and 2.txt...

**Comment by oniony** [comment]
Hmm, thanks for the report. I'll try to recreate this and work out what is
going on.

**Comment by vbgfhfngfdtyreyt** [comment]
More information here. Repair is now failing on a different database / directory. I moved about 30 files from a subdir to the root dir.

repair says the path is updated, but status still shows "!" for each of those files.

**Comment by vbgfhfngfdtyreyt** [comment]
Is there any way I can assist with debugging this? :) Happy to help! Thank you again!

**Comment by oniony** [comment]
Sorry, just been busy. Will try to look this week.

**Comment by oniony** [comment]
OK, I've tried to recreate this but everything works just fine.

The 'no such file or directory' suggests that file may be special in some way that makes TMSU unable to read it (thus causing the repair to fail). Could you please check the file type to make sure it's a regular file with correct permissions?

You say it's now failing on a different path? Is it possible you have multiple TMSU databases in there? Could you have a search for these?

    $ find . -name .tmsu

**Comment by oniony** [comment]
$ mkdir test                                                           ~/projects/tmsu/test
    $ cd test                                                              ~/projects/tmsu/test
    $ ls                                                              ~/projects/tmsu/test/test
    $ mkdir -p foo/bar                                                ~/projects/tmsu/test/test
    $ echo one >foo/bar/1.txt                                         ~/projects/tmsu/test/test
    $ echo two >foo/bar/2.txt                                         ~/projects/tmsu/test/test
    $ tmsu tag foo/bar/1.txt file1                                    ~/projects/tmsu/test/test
    tmsu: new tag 'file1'
    tmsu: 'foo/bar/1.txt' is a duplicate
    $ tmsu tag foo/bar/2.txt file2                                    ~/projects/tmsu/test/test
    tmsu: new tag 'file2'
    tmsu: 'foo/bar/2.txt' is a duplicate
    $ tmsu status                                                     ~/projects/tmsu/test/test
    T ../1.txt
    T ../2.txt
    T ../file2
    T ../file3
    T ../file4
    T ../file6
    T ../foo/bar/1.txt
    T ../foo/bar/2.txt
    T ./foo/bar/1.txt
    T ./foo/bar/2.txt
    $ mv foo/bar/* .                                                  ~/projects/tmsu/test/test
    3
    $ tmsu status                                                     ~/projects/tmsu/test/test
    T ../1.txt
    T ../2.txt
    T ../file2
    T ../file3
    T ../file4
    T ../file6
    T ../foo/bar/1.txt
    T ../foo/bar/2.txt
    ! ./foo/bar/1.txt
    ! ./foo/bar/2.txt
    $ tmsu status .                                                   ~/projects/tmsu/test/test
    ! ./foo/bar/1.txt
    ! ./foo/bar/2.txt
    U .
    U ./1.txt
    U ./2.txt
    U ./foo
    U ./foo/bar
    $ tmsu repair .                                                   ~/projects/tmsu/test/test
    /home/paul/projects/tmsu/test/test/foo/bar/1.txt: updated path to /home/paul/projects/tmsu/test/test/1.txt
    /home/paul/projects/tmsu/test/test/foo/bar/2.txt: updated path to /home/paul/projects/tmsu/test/test/2.txt
    $ tmsu status .                                                   ~/projects/tmsu/test/test
    T ./1.txt
    T ./2.txt
    U .
    U ./foo
    U ./foo/bar

**Comment by oniony** [comment]
Without further information I'm closing this until it's reported again.

**Comment by mbwgh** [comment]
I have this issue right now. `tmsu repair ~/Documents` will crash for me with
```
tmsu: stat /home/mbw/Documents/kit/semester2/swt1/python-bits/venv/bin/python3: no such file or directory
```

with

```
$ file /home/mbw/Documents/kit/semester2/swt1/python-bits/venv/bin/python3
/home/mbw/Documents/kit/semester2/swt1/python-bits/venv/bin/python3: broken symbolic link to python3.8
```

Maybe you are able to reproduce this behavior using a broken symlink?

In any case, tmsu should probably just warn about it and continue.
