### ISSUE TITLE
Root paths relative to database path rather than root directory (/)

### ISSUE THREAD

**Issue by oniony** [oniony/TMSU#15]
@shabbyrobe mentioned in issue #8 that they would like to have relative rather than absolute paths stored in the database:

>TMSU stores the full path to the file in the database, but this limits my ability to either share the database with others or to move it around on my own machine. It makes more sense with my desired workflow to store paths relative to the .tmsu folder, but I understand this limits the existing ability of TMSU to tag files outside a user's home directory.

>One of the main use cases I have for portable, database relative tagging is for the various bands I play or have played in. We share huge collections of snippets and ideas and each band has a distinct set of members so I need one .tmsu folder per band. Being able to tag our snippets in a portable manner using TMSU is the killer workflow upgrade we've been desperate for. I would also like to use it for some photo collections, one private, one to share with my family.

Currently TMSU makes every path absolute before storing them in the database. This has some benefits (e.g. the '..' path element is resolved) but has some limitations:

* External storage mounted under different mount points will break the paths in the database
* The TMSU database is not portable between machines unless identically set up

To solve this problem I think TMSU should not make the paths absolute but should instead resolve paths against a fixed filesystem point. For now, it would make sense to use the parent directory of the `.tmsu` directory of the active database as that fixed point (In the future there TMSU could offer configuration so that this can be changed).

The following operation:

    /home/fred/food $ tmsu tag italian/pizza yum

Would currently store the `pizza` file as `/home/fred/food/italian/pizza`. With this proposed change, using the default database (`/home/fred/.tmsu/default.db`) would store the file as `food/italian/pizza`, (i.e. paths would be relative to the user's home directory by default by virtue of the fact that that's where the `.tmsu` directory is).

If we created a local database at `/home/fred/food/.tmsu/db` (see issue #8), then the path stored would be `italian/pizza`. This would allow the `food` directory to be moved, shared or archived whilst preserving the TMSU database.

But what if the database has been specified with `--database` or `TMSU_DB`? We cannot assume that the specified database is in a `.tmsu` directory. We could either store the paths relative to the database file's directory or we could preserve the existing behaviour of using absolute paths when the database is specified explicitly.

Finally, existing databases will have absolute paths stored so `repair` will need to be upgraded to fix these.

**Comment by 0ion9** [comment]
Very interested to see you moving towards this.. personally this would reduce my database size by 5% (=22mb)

re: handling TMSU_DB / --database :
Could a hybrid approach be used? If the last element of the path is .tmsu (as in "foo/bar/.tmsu/db.py"), then use foo/bar as the fixed point, otherwise use / as the fixed point? Not sure how important this is though -- is there anyone that actually tags files in a location they can't write to the parent of (ie. not in their home dir)?

**Comment by oniony** [comment]
On 1 Jan 2015 11:49, "0ion9" <notifications@github.com> wrote:

> re: handling TMSU_DB / --database :
> Could a hybrid approach be used? If the last element of the path is .tmsu
(as in "foo/bar/.tmsu/db.py"), then use foo/bar as the fixed point,
otherwise use / as the fixed point?

Yes, was thinking about this. I think it's the most sensible approach.

>Not sure how important this is though -- is there anyone that actually
tags files in a location they can't write to the parent of (ie. not in
their home dir)?

I think it's possible, especially if the files are on read-only media.

Unless anyone else has any suggestions or objections we'll go with this.

**Comment by oniony** [comment]
Changes in revision 5aa9c58. Only lightly tested thus far but seems to be working.

To use relative paths in an existing database issue:

    $ tmsu repair --manual / /

**Comment by 0ion9** [comment]
Struggling with the logistics of this currently..

Supposing you have a tmsu database at /home/me/music/.tmsu/db; if you run 'tmsu -v tags /home/me/music/somealbum/01_track01.mp3' and your CWD is not in /home/me/music, tmsu reports 'opening database at /home/me/.tmsu/default.db'.

I can see how there might be some ambiguity there (what if not all filenames are within the pseudo-root directory), but IMO if the database is not explicitly specified, the 'base path' to start searching for .tmsu from should be taken from the first filename argument. 

(I understand this is a little more complicated to implement than the current behaviour).
Using CWD means that hacks like `OWD="$PWD";cd $(dirname "$1");tmsu tags -- "$@"; cd $OWD'  (or forking off a subshell just so you can change working directory) become necessary.

**Comment by oniony** [comment]
OK, thanks, I'll add that behaviour. Hopefully today.

Paul

**Comment by oniony** [comment]
I'm going to leave the current implementation as it is: the local database used relates to the current working directory rather than the arguments passed to the command. The reason for this is that it's a lot more complicated to base the database off of the arguments for various reasons:

* The database cannot be opened until the command line has been parsed
* If there are multiple arguments which one to use for the database, or should multiple databases be opened

And so on.

I'll revisit this post 0.0.5.

>This is the behaviour that a UI showing TMSU tags will encounter, since in general the working directory could be anything at all.

A UI using the VFS will use only the database that the VFS was mounted with.

**Comment by 0ion9** [comment]
> note that both Git and Mercurial use the repository under the current working directory rather than looking at the file arguments.

That's a good point.
I guess OWD="$PWD"; DIRNAME=$(dirname "$1"); cd "$DIRNAME"; tmsu tags "$@"; cd "$OWD" is not too horrendous.

The VFS is great when it relates to your usage; but afaics does not currently relate to the task of 'get tags of $FILE'. I don't see why it couldn't be made to, though, as in 'cat $MNTPOINT/files/home/me/some/music.mp3'. (although probably, to minimize confusion, it paths should be relative to the base dir, eg. the above should be 'cat $MNTPOINT/files/some/music.mp3/space separated tags')

**Comment by oniony** [comment]
Ah, so you are proposing a mechanism in the vfs for viewing the tags for a
tagged file. Might be worth creating a separate issue for that so it does
not get overlooked.

Thanks
Paul

**Comment by 0ion9** [comment]
I started writing up an issue but realized that it would not at all address the issue here: the problem that you have to play around with CWD to get the desired result. It would just relocate that problem to 'need to know what TMSU mounts are active, and determine which one would be used by `cd $(dirname "$1"); tmsu tags "$@"`'. It's possible that the solution is worse than the problem.

**Comment by oniony** [comment]
I'm going to close this issue as fixed. However I appreciate it doesn't fully address all of your concerns. If you are still having problems it might be worth raising another issue (or mulitple issues) on the specific issues remaining. (Just trying to keep the tracker clean so I can see what I need to do.)
