### ISSUE TITLE
VFS directories showing incorrect files in 0.7.2

### ISSUE THREAD

**Issue by taiyu-len** [oniony/TMSU#150]
the fix for #148 made files/=value directories in the vfs work correctly, but now every other directory is broken

given an example set of files in a database
```
bar: x x=v
baz: y
cat: x
foo: x=v
```
the vfs has the following directory contents
```
$ ls mnt/tags
README.md  x  y              # as expected
$ ls mnt/tags/x
files   '=v'  x  y           # y should not be here
$ ls mnt/tags/x/files
bar.2  baz.3  cat.4  foo.1   # shows every tagged file
$ ls mnt/tags/x/=v/files
bar.2  foo.1                 # Correct.
$ ls` mnt/tags/x/y/files
bar.2  cat.4                 # shows files with tag x, but not x=v, and ignores y
$ ls mnt/tags/y
files  x                     # should not show x
$ ls mnt/tags/y/x/files
baz.3                        # shows y files.
```

it seems that the previous tag is being ignored in determining what files and tags to have in the folder  
adding a dummy tag to every file and using it between each directory seems to fix most cases, except for one case which worked in 0.7.0
```
$ ls mnt/tags/x/dummy/files
# in 0.7.2
bar.2  cat.4
# in 0.7.0
bar.2 cat.4 foo.1
```

**Comment by oniony** [comment]
I had messed up a bit of boolean logic to omit value directories. Should be fixed now.
