### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by nkh** [oniony/TMSU#159]
Hi, not a Go developer here so I am most probably doing things wrong.
Go installed (other Go programs run fine), the three dependencies you listed installed as directed.
make/go give the errors below

I also tried to install via the 3 PPA I could find and none worked.

Errors:
CLEANING

go clean github.com/oniony/TMSU
rm -Rf bin
rm -Rf tmsu-x86_64-0.8.0
rm -f tmsu-x86_64-0.8.0.tgz

COMPILING

go build -o bin/tmsu github.com/oniony/TMSU
src/github.com/oniony/TMSU/vfs/fusevfs.go:22:2: cannot find package "github.com/hanwen/go-fuse/fuse" in any of:
	/usr/lib/go-1.10/src/github.com/hanwen/go-fuse/fuse (from $GOROOT)
	/home/nadim/nadim/devel/repositories/TMSU/src/github.com/hanwen/go-fuse/fuse (from $GOPATH)
	/home/nadim/.go/src/github.com/hanwen/go-fuse/fuse
src/github.com/oniony/TMSU/vfs/fusevfs.go:23:2: cannot find package "github.com/hanwen/go-fuse/fuse/nodefs" in any of:
	/usr/lib/go-1.10/src/github.com/hanwen/go-fuse/fuse/nodefs (from $GOROOT)
	/home/nadim/nadim/devel/repositories/TMSU/src/github.com/hanwen/go-fuse/fuse/nodefs (from $GOPATH)
	/home/nadim/.go/src/github.com/hanwen/go-fuse/fuse/nodefs
src/github.com/oniony/TMSU/vfs/fusevfs.go:24:2: cannot find package "github.com/hanwen/go-fuse/fuse/pathfs" in any of:
	/usr/lib/go-1.10/src/github.com/hanwen/go-fuse/fuse/pathfs (from $GOROOT)
	/home/nadim/nadim/devel/repositories/TMSU/src/github.com/hanwen/go-fuse/fuse/pathfs (from $GOPATH)
	/home/nadim/.go/src/github.com/hanwen/go-fuse/fuse/pathfs
src/github.com/oniony/TMSU/storage/database/database.go:21:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
	/usr/lib/go-1.10/src/github.com/mattn/go-sqlite3 (from $GOROOT)
	/home/nadim/nadim/devel/repositories/TMSU/src/github.com/mattn/go-sqlite3 (from $GOPATH)
	/home/nadim/.go/src/github.com/mattn/go-sqlite3
make: *** [Makefile:34: compile] Error 1

**Comment by oniony** [comment]
Could you try creating a directory, let's call it 'gopath' and then set an
environment variable to point to it:

    $ mkdir /some/path/gopath
    $ export GOPATH=/some/path/gopath

Then try go getting the packages and running the build as per COMPILING.md?

The errors you for were basically Go saying it cannot find the dependent
libraries. Setting up a Go path is how you tell Go where to get them to and
where to look when compiling.
