### ISSUE TITLE
What is the difference between TMSU and attr?

### ISSUE THREAD

**Issue by tareefdev** [oniony/TMSU#160]
I was looking for a files tagging solution on Linux platform and ended up with two options, this great tool and [attr](https://linux.die.net/man/5/attr).

I feel they are similar in both purpose and usage, e.g setting a tag
`tmsu tag test.md art`
`setfattr -n user.tag -v "art" test.md`

Also to search for a file has a tag I could use `tmsu files` or other tools available for attr like Recoll, Baloo etc

So I thought maybe it's helpful to add some information related to this question on the wiki.

**Comment by oniony** [comment]
I'd not heard of that one, I'll have a look at it.

**Comment by oniony** [comment]
Oh, sorry, it's extended attributes. I've obviously heard of them.

I remember I did consider using them when starting the project but I read
that they can easily get lost when moving files about as they're not always
supported. Plus setting the attributes modifies the files.

Certainly I could add something to the wiki comparing the two.

**Comment by tareefdev** [comment]
Thanks for the quick reply. It's [possible](https://wiki.archlinux.org/index.php/File_permissions_and_attributes#Preserving_extended_attributes) (partly?) to preserve extended attributes, e.g `mv` is preserving by default, `cp` needs `--preserve=mode,ownership,timestamps,xattr` as a flag and so on.

**Comment by oniony** [comment]
Sure, but if you move a file to a filesystem that does not have support
them they'll be silently lost, for example.

Plus I really wanted TMSU to be a 'walk away' affair whereby the files are
not changed by the tool so you can end up where you started if you don't
like it for whatever reason. That way it's a risk free buy-in. It also
means it works on read-only filesystems and files as the tag meta-data is
separate.

Those are the main differences anyhow.

**Comment by tareefdev** [comment]
Great! Yeah absolutely it's great to have those two options, I just wanted to focus on the real differences between them so that we can pick one for the right use case.

**Comment by tareefdev** [comment]
Also, it would be great if you add a section for developers, for example, I consider writing a package for Emacs to enhance supporting tags on Dried (Emacs default file manager), it would be as an interface to set, get tags and query files based on them, so I wonder which the best tool here too

**Comment by defaultxr** [comment]
@tareefdev Obviously it's been a while since this was posted, but I am interested in the Emacs/TMSU interface you mention, if you ever ended up writing anything for that.

**Comment by tareefdev** [comment]
@defaultxr unfortunately, I didn't. Learning Lisp goes slowly with my available time
