### ISSUE TITLE
Please provide debian package

### ISSUE THREAD

**Issue by anishmittal2020** [oniony/TMSU#161]
Hi please provide a debian package as a considerable number of users could benefit from it. Instead of closing this issue you could tag it has help required. 

Especially Ubuntu has a lot many users.

**Comment by oniony** [comment]
I do not have the time, energy or inclination to provide packages for x, y or z distro. TMSU is fairly easy to install from source and there are full instructions in the COMPILING.md file. Just download a zip of the latest from GitHub (or clone the repo) and follow the instructions.
