### ISSUE TITLE
cannot mount VFS

### ISSUE THREAD

**Issue by TheOncomingStorm** [oniony/TMSU#163]
Everything else in tmsu seems to work just fine but when I try to mount the VFS with "tmsu mount mp" I get the following. 

```
tmsu: virtual filesystem mount failed: /usr/bin/fusermount: unknown option ''
tmsu: could not mount virtual filesystem at 'mp': could not mount virtual filesystem at 'mp': fusermount exited with code 256
```
I have read that this might be an issue with gvfs or go-fuse but when I traced down those issues they were **supposedly** fixed as of a month ago or more. 

What can I do to debug this so I can give you better info here?

**Comment by TheOncomingStorm** [comment]
Ok, running the daemon directly seems to work. I'll have to play with it a bit to be certain but it does have the query and tags sub-directories so that seems like a win so far..

My fusermount version is 2.9.9.

**Comment by oniony** [comment]
I'll investigate further: I'm a version behind you and I can see they made
some changes in 2.9.9 to the allow_other option which may have broken the
way I'm calling it.

**Comment by oniony** [comment]
I have updated my FUSE to 2.9.9 and cannot reproduce your problem. I have also updated to the latest go-fuse and the 'mount' subcommand is still working fine for me.

* Which operating system are you using?
* Are you simply running `tmsu mount mp` without any extra arguments?
* Do you have any TMSU shell aliases set up?
* Which version do you get when you run `tmsu --version`?

Thanks in advance.

**Comment by TheOncomingStorm** [comment]
I'm using Gentoo(mostly up to date as of last month). Yep, just "tmsu mount mp" and nothing else, including shell aliases. 

tmsu -V says   TMSU 0.7.0 which is a little behind github but it's the version that Gentoo is compiling. I tried compiling from github but am having problems retrieving the Go packages. It *says* it got them and then can't find them(and I have no clue where it might be putting them if it did).

**Comment by oniony** [comment]
The packages go to wherever you have GOPATH set to...I forget where if you
don't have this set. Definitely make sure you have this set.

Also, which shell are you using?

**Comment by TheOncomingStorm** [comment]
Ok, once I set GOPATH, it compiled no problem. It seemed to be set somewhere but not in my shell, which was bash, btw. 

Once I updated to 0.8.0, mounting worked no problem so I guess I'm gonna close this.

**Comment by oniony** [comment]
Excellent, glad it's now working for you. Thanks.
