### ISSUE TITLE
Tagging things programmatically

### ISSUE THREAD

**Issue by HenryMarshall** [oniony/TMSU#165]
I'm interested in tagging content programmatically based on the data in [Kodi NFO files](https://kodi.wiki/view/NFO_files) (which contain actor, genre etc). Would you recommend I achieve this through the normal API by shelling out from my script? Alternatively, am I asking for trouble if I were to edit the sqlite database directly?

As an aside, TMSU is awesome, thanks for making it!

**Comment by oniony** [comment]
Probably the safest, in terms of data integrity, is to call TMSU. I've been
wanting to expose an embeddable version for some time but I need to find
some time to do the refactoring to sort this.

You could write to the database directly, it's just an Sqlite database at
the end of the day, but there's the risk you'll leave orphan items or that
I change the schema in the future.

**Comment by HenryMarshall** [comment]
Cool. My use case is, for the most part, write once and never update, so I'll just call TMSU directly. I'll leave a comment here with a link to the script I create in case it is of any use to someone else who uses TMSU. 

Thanks again.
