### ISSUE TITLE
[Feature request] tmsu delete should allow you to merge in-line.

### ISSUE THREAD

**Issue by ashleyharvey** [oniony/TMSU#171]
When deleting a tag with `tmsu delete foo`, it would be nice to be able to supply a tag for the files tagged with `foo` to obtain a new tag, or `tag=value` pair.  Alternately maybe there should be a rename feature, although this doesn't accomplish the same thing.  Sometimes in the heat of the moment I tag a file when a better thing to do is assign a tag=value pair.  I might tag multiple files this way, before realizing what I've done.  At that point I have to pull up a list with `tmsu files`, and individually re-tag those files with my new tag before untagging all of them from the old tag and then deleting the (old) tag.

Maybe we could call this `tmsu migrate`.

**Comment by oniony** [comment]
You can apply a tag to already tagged files:

    tmsu tag --where=sometag newtag

You can rename tags (and values):

    tmsu rename tag newname
    tmsu rename --value value newname

You can merge tags:

    tmsu merge losetag keeptag

Is there anything you wanted to do you can't do with these existing
facilities?

**Comment by ashleyharvey** [comment]
Okay -- looks like I didn't do enough of my own research, and I mis-understood how tag=value works; the value is actually a tag and can be manipulated as such.  My issue can be solved quite easily in two steps.

Thanks, and sorry for wasting your time.  I really should've done more of my own research before opening the issue.
