### ISSUE TITLE
Support common file operation in VFS

### ISSUE THREAD

**Issue by xofyarg** [oniony/TMSU#173]
Hi,

I've been using TMSU for some time, and often try to cp/mv files in VFS, turned out to a "Function not implemented" error. Maybe this has been discussed before but I didn't find anything, is it possible to support managing tags by other tools? E.g. inside VFS, cp a file from one directory to another apply the tag internally, mv is similar but remove the previous tag as well.

BTW, is there any documentation covers the design consideration on symlink over virtual file? I understand it's safe to use symlink, but by using virtual file, file edit and rename can all be handled inside the VFS I guess.

**Comment by emarj** [comment]
This would be a killer feature!

**Comment by oniony** [comment]
It already does some of this stuff. See the wiki.
