### ISSUE TITLE
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by tmsu)

### ISSUE THREAD

**Issue by Mikeinnc** [oniony/TMSU#176]
Hello - after reading various very good reviews on this application, I thought I would load it on my Linux Mint 19.2 'Tina' laptop. However, it will not load correctly and I get the following error message if I try to run it:

tmsu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by tmsu)

Searching the internet is giving me palpitations - reading, for example, that I need to recompile my entire operating system etc!! There must be an easier answer to this issue - and I'd be very grateful if someone could advise me (and save me from possible heart failure!!!) After all, it's not like Mint is a little used system.......

Thanks very much in advance

**Comment by oniony** [comment]
Hi Mike,

How are you building TMSU? Are you compiling it yourself or downloading a
binary from somewhere?

From what I can tell on
https://www.distrowatch.com/table.php?distribution=mint, Mint is currently
shipping with a slightly older glibc library.

If you're using someone else's binary then you'll be at the mercy of
whatever versions they compiled with. TMSU is pretty easy to compile
yourself, if you're feeling up to it, but you will need to download and
install Go. Instructions are in the COMPILING file in the TMSU repository.

Paul

**Comment by Mikeinnc** [comment]
Phew! Thanks so much, Paul. Yes, relatively easy and certainly not heart failure stuff! Very clear instructions and no real problems - apart from the go get commands seemingly putting the necessary files in a directory where 'make' couldn't find them. Quickly solved, though, by cloning them into the TMSU/src directory and make then ran very happily. And, as expected, all is good! Thanks again - I'm looking forward to using TMSU to tag my files. As this is fixed, I'll close the issue. Regards - Mike

**Comment by oniony** [comment]
Just out of interest, where did you hear about TMSU?

**Comment by Mikeinnc** [comment]
Hi Paul

I subscribe through my local public library to the electronic version of
the UK magazine, 'Linux Format'. There was an article - "Tagging Files made
Easy:...using smart tools such as TMSU" - in the August issue (p62) that
discussed TMSU (and is completed in this month's issue, although I haven't
read that yet). Some years ago, I used Tabbles on a Windows machine to tag
files, so I was used to - and appreciated - the tagging of files.
Incidentally, although I was originally and very kindly given a free copy
of Tabbles to use with some volunteer (ie not for profit) work I perform,
the licence on that expired, and the company has moved to a subscription
basis and wouldn't offer a new licence without payment - something I will
not and should not have to do for volunteer work for which I get no
payment! So - no more Tabbles! The article on TMSU re-sparked my interest,
and as I have a Mint laptop, I thought I would see how well it performed.
You will have seen that I successfully built a copy, and it is now 'in
action', so to speak, although I haven't had much time yet to explore it.

Thanks for all your efforts! Much appreciated.

Mike

**Comment by bitwombat** [comment]
I'm going to pile onto this issue because I'm getting the same thing with the binary from https://github.com/oniony/TMSU/releases/tag/v0.7.4 on an Ubuntu 18.04.03 system.

Should this be so, and the answer is to compile myself? 

BTW, the same article showed up in Australia's APC magazine, Oct 2019, page 96.

**Comment by oniony** [comment]
The solution is to either use a binary compiled with a version of Glibc you
are actually using or to compile yourself. If the binary is compiled witha
more recent version that your distro uses then you get these kinds of
errors.

Compilation is actually pretty easy, the instructions are in COMPILING.md,
but you will need to download Go to do so. It should take only five minutes
once you have Go installed.

Unfortunately there is no Ubuntu package so options are either manual
binary installation or compiling from source.
