### ISSUE TITLE
option to display time

### ISSUE THREAD

**Issue by ddombrowsky** [oniony/TMSU#177]
I see there's a `-s time` flag in `tmsu files`, but there is no way to print that timestamp, short of actually going into the database and looking at the table.  

Am I missing an option somewhere, or does it not exist?

**Comment by oniony** [comment]
There's no way to view the field in TMSU. But in an up to date database the
mod timestamp is just a reflection of the mod timestamp of the file itself,
which you can view with 'ls'.
