### ISSUE TITLE
SHA256 fingerprint incorrect for large files

### ISSUE THREAD

**Issue by joe-rice** [oniony/TMSU#178]
The default SHA256 fingerprinting method seems to disagree with `sha256sum` reliably for files over ~5.3MB. Recomputing hashes with `tmsu repair --unmodified` didn't correct the issue.

    $ sqlite3 -noheader -separator ' ' .tmsu/db 'select fingerprint, name from file;' | sha256sum -c
    ...
    8aec7781956264bc6ec48e306334c0d4e23cad8852295ceed8c460b0dd59878d: OK
    2a674442fd5076f1083da048c095c1c6b5181488f05badc42b3759ae3bff2d77: FAILED
    5af4ea8edbfa950948818ccd91cbcdf43f6ba27a71c3d21bafbf35ac5375aa86: OK
    sha256sum: WARNING: 11 computed checksums did NOT match

I've tested this with v0.7.4 (ArchLinux v0.7.4-1) and master (v0.8.0~1e6dab). Only the one machine.

I'll dig into it and submit a PR sometime after the holidays--assuming this behavior is unintentional.

**Comment by oniony** [comment]
https://github.com/oniony/TMSU/wiki/Fingerprint-Algorithms#algorithms

**Comment by joe-rice** [comment]
I spoke too soon. Apologies. It's very well documented.
