### ISSUE TITLE
Have you considered dropping FUSE for sym-links

### ISSUE THREAD

**Issue by Jwink3101** [oniony/TMSU#179]
I am considering leaving my current tag system (which I wrote) for TMSU. When I wrote mine, I wanted something similar to your FUSE mount where you can see things by tags but I didn't want to deal with FUSE. I opted instead for a simple tool that will make a directory of symlinks (relative or absolute) to the files. It works really well and I do not have to deal with FUSE.

Have you considered something like that?

**Comment by oniony** [comment]
Yes, but then you can't really identify files with multiple tags. I decided
early on that a virtual filesystem would have the most benefit.
