### ISSUE TITLE
Make query tag case insensitive

### ISSUE THREAD

**Issue by limelime** [oniony/TMSU#18]
Can you make query tag case insensitive.
For example:
```bash
# Should also list files tagged as 'Mp3'.
$ tmsu files mp3
```

I'm using TMSU 0.4.3.

**Comment by oniony** [comment]
Hi there,

I don't think case insensitivity by default is a great idea. However there has been a request for wildcards in tag matching so I think case insensitivity (as an option) would fit in quite well with that piece of work.

In the mean time, as a workaround, you could merge your tags with different spellings:

    $ tmsu merge Mp3 MP3 mP3 mp3

That will leave you with the last one 'mp3' which will be applied to all of the files the other spellings were applied to.

**Comment by oniony** [comment]
In fact, on second thoughts I can add this option now.

**Comment by oniony** [comment]
I've pushed this back to post 0.5.0. I'll probably complete it now as part of the wildcard support as I originally thought. Sorry to disappoint you.

**Comment by oniony** [comment]
Sorry this took so long. I've now added --ignore-case to the 'files' subcommand for case insensitivity.
