### ISSUE TITLE
built-in batch *automatic* move/rename

### ISSUE THREAD

**Issue by mope1** [oniony/TMSU#187]
Hi there! Cool project, but I have some doubts it will get much love when, for example, a cool `Nautilus` mod exists for it, but the files and folders still loose all tags upon being moved even from that same Nautilus file manager.
Especially since a common usecase would, imho, consist of migrating an an existing file tree from a deeply nested folder structure to a less deeply nested one but with `TMSU` metadata.
To accomplish this, a user would intuitively try tagging files in their original place and then move them to the new place. Which destroys all the tags again.

Obviously this migration tasks could also be accomplished with a bunch of shell scripting and whatnot, but by eliminating this requirement, many possible applications in e.g.  more enterprisey or sciency environments would become available.

So anyways, any thoughts on re-adding some sort of fast, opportunistic recursive fingerprinting https://github.com/oniony/TMSU/issues/17 and then adding a command dedicated to repairing the symlinks to folders and files that were *only* moved? 

The idea of such a command, let's call it `repair_moved` for now would be that for example the Nautilus integration, upon finishing some rename/copy/move operation, would be hooked to call the `repair_moved` function, which would cause a partial reindex of the files from disk. Then, `TMSU` would find the moved folders and restore the tags like a user might expect. From the perspective of the user, it would look like the file copy operation is hanging on 100% for a bit. 

Obviously, this is going to break in cases where the files are modified and then moved, for example. That problem might be solvable with a `reindex` command/hook function that would trigger another partial reindex before the file copy operation is begun etc. Im getting into the weeds here and have not looked at the Nautilus extension itself yet (sorry, my bad, i will edit this after), but in any case, the folder fingerprinting index could make solving some of the other issues here in the `TMSU` issue tracker easier as well.

Of course, my suggestion only makes sense if TMSU actually *wants* to be a somewhat user-facing automation tool (on the command line or otherwise), rather than some sort of skeleton shell API *just* for tagging files. 

Thanks for your attention and, possibly, feedback!

**Comment by oniony** [comment]
tmsu repair --manual already exists

**Comment by mope1** [comment]
ok sorry i just noticed i forgot to research a bunch of stuff, will come back later and probably just close this, thanks!

**Comment by mope1** [comment]
Alright here is the relevant docs: https://github.com/oniony/TMSU/wiki/Repairing#Manual%20Repair
I actually saw this, but that is what I would call a "shell API" and does not scale for a human user. My issue/suggestion stands, and I will have a look at the nautilus integration now
