### ISSUE TITLE
CIFS "database is locked"

### ISSUE THREAD

**Issue by rkelly** [oniony/TMSU#197]
When trying to initialize a folder that is on a CIFS mount, the program hangs for a bit, then returns an error.

```
$ tmsu init
tmsu: /mnt/share/Scary: creating database
tmsu: /mnt/share/Scary: could not initialize database: database transaction error: database is locked
```

A `.tmsu` folder is created with a `db` file within it. However, any TMSU command returns the same error.

Here are some of the mount attributes I have in effect.

cifs (rw,nosuid,nodev,noexec,relatime,vers=1.0,sec=ntlmv2,cache=strict,forceuid,gid=100,forcegid,soft,unix,posixpaths,serverino,mapposix,acl,rsize=61440,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1,user)

TMSU appears to work fine on non CIFS mounts on my system.

Thanks!

PS: This [SuperUser question](https://superuser.com/questions/1492251/tmsu-error-database-is-locked-when-trying-to-create-a-database-outside-local-hom?newreg=b2edae98c6904f9d9c0c3ea6f9a8b235) seems to refer to the same issue I'm encountering.

**Comment by paulie-g** [comment]
a) try disabling locking, the parameter is 'nolock' iirc
b) sqlite on CIFS is a bad idea (NFS too for that matter)
