### ISSUE TITLE
Can't initiate default.db

### ISSUE THREAD

**Issue by AlbusSeveriusPotter** [oniony/TMSU#24]
I can't create/access a new default database when running 0.5, but works fine with 0.4.3. The messages I get when I run any tmsu command:

> tmsu: creating database at '/home/[username]/.tmsu/default.db'.
> tmsu: could not open storage: could not open database at '/home/[username]/.tmsu/default.db': database transaction error: unable database file

Creating the database with 0.4.3 and then manually "repair" (modify to relative paths) in 0.5 works fine without problems.

After trying to create a new database with 0.5 I can't find any ".tmsu" directory (or a default.db file) in $HOME.

**Comment by oniony** [comment]
I've just tested this and it is working fine on my machine:

    $ rm ~/.tmsu/default.db
    $ tmsu tags
    tmsu: creating database at '/home/paul/.tmsu/default.db'.
   $ sqlite3 ~/.tmsu/default.db
   sqlite> .schema

Everything looks fine.

Does the 'init' command work?

**Comment by AlbusSeveriusPotter** [comment]
No command work. Every `tmsu` command results in an error.

After testing the commands you posted I found out that it doesn't work then I don't have a `~/.tmsu` directory, but works perfectly then I it exists. If you would have executed `$ rm ~/.tmsu` instead of `rm ~/.tmsu/default.db` you would get the error message.

**Comment by oniony** [comment]
Ah hah! I'll try that.

**Comment by oniony** [comment]
Thanks for reporting this.

Fixed in 9442633.
