### ISSUE TITLE
Remove file entirely from database

### ISSUE THREAD

**Issue by TheChymera** [oniony/TMSU#243]
`tmsu repair .` or even `tmsu repair myfile.ext` will notify me that the file is gone, yet it still shows up when I run `tmsu tags myflie.ext`.

How can I remove it from the database entirely after deletiong? I was thinking untagging would do the trick, but I need to specify all flags or pipe them in from tmsu reporting.... There needs to be a better way for just deleting files, right? I have checked the man page and help text, yet nothing seems to fit.

This is all going on on `=tmsu-0.7.5`, but I'd be happy to test the live version if this is something that really isn't there but would be implemented.

**Comment by 0ion9** [comment]
That's what `tmsu untag --all $FILENAME` is for.

**Comment by TheChymera** [comment]
Thanks, that solved it!
