### ISSUE TITLE
Question: what does the error message mean?

### ISSUE THREAD

**Issue by nkh** [oniony/TMSU#259]
$> tmsu tag '/home/nadim/nadim/devel/repositories/ftl/the space file' admin

tmsu: '/home/nadim/nadim/devel/repositories/ftl/the space file' is a duplicate

**Comment by oniony** [comment]
It's not an error, it's simply telling you that you have another file with
the same contents. See `tmsu dupes`.

**Comment by nkh** [comment]
Can we hope for an option, for the command line, to not show that information in the next version?

**Comment by oniony** [comment]
Set `reportDuplicates` to false.
