### ISSUE TITLE
tmsu imply should create new tags if necessary

### ISSUE THREAD

**Issue by mszczepanczyk** [oniony/TMSU#26]
now:

~~~
$ tmsu imply new_tag some_tag
tmsu: no such tag 'new_tag'
$ tmsu imply existing_tag new_tag
tmsu: no such tag 'new_tag'
~~~

**Comment by oniony** [comment]
Thanks for reporting this. I'll fix this so that `imply` follow the `autoCreateTags` setting. This will likely be in a couple of days time.

**Comment by oniony** [comment]
Sorry this took so long.

You should find it in 7a0dfb4.`

**Comment by mszczepanczyk** [comment]
Thanks a lot!
