### ISSUE TITLE
MS Windows binary for TMSU

### ISSUE THREAD

**Issue by limelime** [oniony/TMSU#34]
Is there any plan to provide executable binary for MS Windows platform?
I wrote a [set of Lua scripts](https://github.com/limelime/xmpv) to extend MPV media player. It uses TSMU as a backend. I would like to be able to use my scripts in Windows too.

thx!

**Comment by oniony** [comment]
I made a Windows binary for 0.5.0 and it's on hi GitHub releases page but it's quite buggy and there's no VFS. However I do plans to do this: it's just a matter of finding time. Most of TMSU development I do on the train on my commute using a Linux netbook so Windows support requires I spend time at home, which is in short supply. However I will get around to this, including VFS support I just give and indication as to when.
