### ISSUE TITLE
tsmu-fs-mv drops tags on to new directory

### ISSUE THREAD

**Issue by jsqliu** [oniony/TMSU#36]
Testing off commit 36de52af918a755d995cd5091c5a38a5ec3cf6d0

> tsmu-fs-mv curdir/filename newdir

curdir/filename moves to newdir/filename
tags move from curdir/filename to newdir

**Comment by 0ion9** [comment]
I suggest `mv "$1" "$2" && (DEST="$2"; DEST="$2" if [ -d "$2" ]; then BASE=$(basename "$1"); DEST="$DEST/$BASE"; fi; tmsu repair --manual "$1" "$DEST")`. I have tested this and it appears to work correctly for both cases (that is, "destination is an existing directory" and "destination is a filename")

Note the liberal use of quoting. The current script does not use them and so will break on files containing spaces or other special characters. The same problem is present in tmsu-fs-rm and tmsu-fs-merge.

**Comment by oniony** [comment]
Thanks guys.

Quotation marks in fe9c59b.

**Comment by oniony** [comment]
@0ion9 Thanks for the fix: this is integrated in 158631f.

**Comment by jsqliu** [comment]
Thanks for the quick solution and update 0ion9 and oniony.
