### ISSUE TITLE
symlinkTargetNameNoExt: Fall back on regular hashing for regular files.

### ISSUE THREAD

**Issue by eigengrau** [oniony/TMSU#40]
I was trying to set up TMSU for use within a git-annex repository, and was delighted to see the `symlinkTargetName{,NoExt}` option exist. However, it seems that when a regular (non-symlinked) file is tagged, tmsu will still use the name as the fingerprint (despite what the option name indicates). Would it be reasonable to fall back to a regular hash for non-symlinked files? Perhaps by specifying the desired digest in a setting, such as `symlinkTargetNameNoExt,dynamic:SHA1`?

In the best case, tmsu could also fall-back to its regular behavior when the file is a symlink, but the target name is not “special”. If the config option is meant to target git-annex interoperability, git-annexes known key formats could be used as a pattern against which to match; alternatively, it could be checked whether the symlink goes to `[…]/.git/annex`. Or, for a more generic solution, maybe a config option specifying a regular expression might be viable?

Thanks for making TMSU!

**Comment by oniony** [comment]
The `symlinkTargetName` and `symlinkTargetNameNoExt` were added at the request of another user who was trying to use TMSU with Git Annex.

Yes it would be possible to fall back to regular hashing in the case of regular files but as you have expressed this would be somewhat hard to configure with the current set-up. One solution is the comma-seperated list of preferences as you proposed; another would be to split out the configuration of the hash algorithm for each type of file. Already TMSU allows files and directories to be configured separately so perhaps this could be extended to allow symbolic links to be separately configured?

**Comment by oniony** [comment]
>In the best case, tmsu could also fall-back to its regular behavior when the file is a symlink, but the target name is not “special”.

This would be a lot more complex to implement and configure but I will have a think about how it could work.

**Comment by oniony** [comment]
So what I've done is to:

1. Remove support for the `symlinkTargetName` and `symlinkTargetNameNoExt` values of the `fileFingerprintAlgorithm` setting.
2. Added a new setting called `symlinkFingerprintAlgorithm` with the following possible values:
  * `none` -- use empty fingerprints
  * `follow` -- use the fingerprint of the target file
  * `targetName` -- use the target file's name
  * `targetNameNoExt` -- use the target file's name with the extension removed
3. Added automatic upgrade logic to populate `symlinkFingerprintAlgorithm` where `fileFingerprintAlgorithm` is currently `symlinkTargetName` or `symlinkTargetNameNoExt`. The only thing to note with this is that it will also then delete the `fileFingerprintAlgorithm` setting such that the default will be used for regular files.

**Comment by eigengrau** [comment]
This makes the symlink handling more consistent! Thanks! :+1:
