### ISSUE TITLE
Cannot apply tags if there is a circular implication

### ISSUE THREAD

**Issue by oniony** [oniony/TMSU#42]
Consider the following:

    $ tmsu imply apple banana
    $ tmsu imply banana apple
    $ tmsu tag somefile apple
    $ tmsu tags --count somefile
    0

Neither tag is applied because TMSU has logic to not explicitly apply implied tags. However the logic is flawed as when there is a circular dependency it is not clever enough to realise it needs to break the circle and apply the first tag.

This problem also exists with larger chains:

    $ tmsu imply aubergine broccoli
    $ tmsu imply broccoli cauliflower
    $ tmsu imply cauliflower aubergine
    $ tmsu tag somefile aubergine
    $ tmsu tags --count somefile
    0

**Comment by 0ion9** [comment]
Personally, I would expect circular dependency to raise an explicit error*. Possibly with an option to force TMSU to make the implication anyway, but IMO in general circular implication indicates user error.

So to be more concrete, I would expect
`tmsu imply banana apple` and `tmsu imply cauliflower aubergine` to raise errors.

* The only use case, aside from 'wreaking confusion', I can see for circular dependency is synonyms (banana == apple and apple == banana). But IMO the proper way to implement synonyms is via an aliasing system (eg. where querying apple gets you apple and querying banana gets you apple.. and maybe querying any_fruit gets you 'apple or orange or pineapple..')

**Comment by oniony** [comment]
I have considered prohibiting them to be honest as working out which tags to apply is quite tricky when there are circles. The only reason I originally included them was because they provided 'free' synonyms, as you mentioned.

I guess I could prohibit their creation without necessarily requiring users to delete any existing ones.

**Comment by oniony** [comment]
Creation of implication cycles is now prohibited. However I've not made any changes or scripts to address any existing ones, so anyone with an existing cycle may still hit this bug when applying the set of tags.
