### ISSUE TITLE
Completion for tag values

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#44]
For example, I tend to use tagvalues to define sets, using the tag { -- or occasionally the tag storyboard, etc, according to exactly what it is. The existing 'tmsu values $TAGNAME' interface supports this, so it would be nice to be able to type `tmsu files {=<tab` and get a list of sets (the output of `tmsu values "{"`, approximately)

The current behaviour is that no options are offered when Tab is pressed on `tmsu files sometag=`.

(btw (offtopic): integration test is currently failing on master, with lots of error messages referring to RECURSIVE, like this: `./merge/merge_two_tags_nonexistant_source_tag [PASS]
4d3
< tmsu: could not query files: near "RECURSIVE": syntax error ./merge/merge_two_values [FAIL]`)

**Comment by oniony** [comment]
It will offer suggestions if you add spaces:

    tmsu files tag = <tab>

I can't remember the reason for this behaviour (I'm sure there was a good one) but I can certainly look into it.

I'll look into the integration tests. Perhaps the 'with recursive' feature of Sqlite that is not in your version.

**Comment by oniony** [comment]
I think the integration test failure might be down to the version of Sqlite3 you are using. The continuous [integration passed](https://drone.io/github.com/oniony/TMSU/latest) and the tests passing on my box too.

I am using Sqlite3 3.8.7.2. Could you please confirm your version and which distro you use?

**Comment by 0ion9** [comment]
Actually it looks like TMSU is completely broken for some cases (eg. `tmsu files` is currently not working at all), so I guess I need to update go-sqlite3.

EDIT:
Yeah, updating go-sqlite3 fixed the errors and `tmsu files` works again :)

**Comment by oniony** [comment]
>BTW: I have tested the tmsu files tag = <Tab> method: it works for my tag 'd' and 'storyboard' but not for my tag "{" -- no matter how it is quoted or escaped.. So I think maybe the completion code is forgetting to quote the tag name when asking for completion candidates.

OK, thanks for the clarification. I'll see if I can get it to work.

**Comment by oniony** [comment]
A value of `{` works fine for me with a simple backslash escape `\{`. Indeed Zsh suggested this form after pressing tab twice.

**Comment by oniony** [comment]
I've modified the Zsh completion script to allow completion if the '=' is immediately after the tag name. I cannot do this (easily) for the other symbol operators (!=, <, >, <= and >=) as they need to be escaped in most shells.

Anyhow, you should now be able to do:

    tmsu files year=⇥

And get completion.
