### ISSUE TITLE
Tag Value Directories Duplicated on VFS

### ISSUE THREAD

**Issue by knickum** [oniony/TMSU#46]
Multiple identical directories are being created for tag values, test case:
```bash
> tmsu tags
Genre
> tmsu values
SciFi
> tmsu files
first_contact.avi the_wrath_of_khan.avi
> tmsu mount /media/test
> tree /media/test/tags/Genre
/media/test/tags/Genre/
|-- first_contact.1.avi
|-- =SciFi
|    |-- first_contact.1.avi
|    |-- the_wrath_of_khan.2.avi
|-- =SciFi
|    |-- first_contact.1.avi
|    |-- the_wrath_of_khan.2.avi
|-- the_wrath_of_khan.2.avi
```

Each additional file tagged with `Genre=SciFi` will add an additional (identical) `=SciFi` directory.

Expectation would be a single `=SciFi` directory.

```bash
> tmsu version
TMSU 0.6.0
....
```
Please let me know what additional information would be helpful.

I tried looking into the src code a bit, assuming I just need to change something along the lines of

```
show directory
```

into

```
if not directory.exists then
    show directory
```

But don't know Go or VFS arch. Will try to look into more later. Maybe a book-keeping dictionary?

```
visited = {
    'Genre': ['SciFi'],
    ....
} 
```
...
```
if directory not in visited:
    show directory
    visited[tag] += directory
```

**Comment by oniony** [comment]
Hi, thanks for reporting this. My guess us the codes walking the set of filetags rather than values. I'll have a look a little later on today as it should be pretty trivial to fix.

It's made me realise there's no test coverage around the virtual filesystem do I'll need to look into that too afterwards.

**Comment by oniony** [comment]
Should be fixed now, please reopen if this is not the case.
