### ISSUE TITLE
tag --replace option

### ISSUE THREAD

**Issue by c0ffeeartc** [oniony/TMSU#47]
Hello, is it possible to replace tags in one command, similar to:
```
$ tmsu tags ./file
foo bar
$ tmsu tag --replace --tags="foo new" ./file
$ tmsu tags ./file
foo new
```
I wrote ui script [tmsu-tagd](https://github.com/c0ffeeartc/tmsu-tagd) , it edits tags of one file. In implementation it stores list of tags and for retagging it does:
```
$ tmsu untag --all ./file
$ tmsu tag --tags "foo new" ./file || tmsu tag --tags "foo old" ./file
```
So it always untags all and then tags again, which isn't very nice.
Is replacing tags in one command already available or will it be in future?

**Comment by oniony** [comment]
No, there is no such functionality. I'll have a think about this. It might
make sense to consider this as a part of a larger piece of work to do
operations based upon what tags are already applied, e.g.

    $ tmsu tag --where="tag1 or tag2" tag3
    $ tmsu untag --where="tag4 and tag5" tag5

And so on.

Hello, is there such functionality - to replace tags in one command, like
this:

$ tmsu tags ./file
foo bar
$ tmsu tag --replace --tags="foo new" ./file
$ tmsu tags ./file
foo new

I wrote ui script tmsu-tagd <https://github.com/c0ffeeartc/tmsu-tagd> , it
stores list of tags and for retagging it does:

$ tmsu untag --all ./file
$ tmsu tag --tags "foo new" ./file||tmsu tag --tags "foo old" ./file

So it always untags --all and then tags again, which isn't very nice.
I'd like to know if --replace functionality is already available or will be
in future.

—
Reply to this email directly or view it on GitHub
<https://github.com/oniony/TMSU/issues/47>.

**Comment by oniony** [comment]
As a workaround, you should be able to accomplish this with `xargs`:

    $ tmsu files tag1 | xargs -I {} tmsu tag {} tag2
    $ tmsu files tag1 | xargs -I {} tmsu untag {} tag1

But it may be easier to simply use:

    $ tmsu merge tag1 tag2
    $ tmsu --create tag1

**Comment by c0ffeeartc** [comment]
Hello, didn't know about `tmsu tag --create tag1`.
My goal is to modify tags of one file, with minimal calls to `tag`, `untag`.

 `tmsu tag ./file --tags "tags disabled previously but enabled in script" || tmsu untag ./file --tags "tags enabled previously but disabled in script"`. 

My script returns list of all enabled tags in the end, and `tmsu tag` can work with it nicely. And for `untag` I'll track `enabled-to-disabled` list inside script.
