### ISSUE TITLE
tmsu help repair -> 'could not open storage: .. database is locked'

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#48]
Just encountered this message when trying to look up help for 'repair' (`tmsu help repair`) while 'tmsu repair -u' was running in another tab.

This is a minor bug, I guess, but it doesn't seem that extraordinary that the user might want to look up help while TMSU is running, and I don't see any reason that the help command should actually need a db lock.

**Comment by oniony** [comment]
Hmm, strange. Thanks for reporting. I'll take a look.

**Comment by oniony** [comment]
This is a hangup from when TMSU used to read multiple commands from standard input: in order for all of the commands to be completed within a single transaction the database had to be opened for the duration of the process.

Some time ago I removed the ability to run multiple commands from standard input in favour of having reading from standard input on a per command basis (at this time only 'tag' can do this). It appears I never fully cleaned up by moving the opening/closing of the database back to the individual commands.
