### ISSUE TITLE
Please use package-relative import paths in *.go

### ISSUE THREAD

**Issue by stapelberg** [oniony/TMSU#50]
Currently, files such as src/tmsu/cli/cli.go contain:
```go
import (
    "fmt"
    "os"
    "os/user"
    "path/filepath"
    "tmsu/common/log"
    _path "tmsu/common/path"
)
```

This prevents me from building TMSU by using `go get -u github.com/oniony/TMSU/src/tmsu/cli` (which I realize is not what you are recommending), and makes packaging your software (e.g. for Debian) unnecessarily hard.

Could you please switch to import paths such as `github.com/oniony/TMSU/src/tmsu/common/log`, as is customary when writing and publishing Go code?

Thank you for considering.

**Comment by oniony** [comment]
Thanks for reporting this. I'll have a look tomorrow morning.

**Comment by oniony** [comment]
I've packed the wrong PSU for my laptop so I won't be able to look at this
today. I'll hopefully get it sorted Wednesday evening/Thursday.

**Comment by oniony** [comment]
I've just realised I've used the wrong case in the URL. I'll fix this up this evening. Sorry about that.
