### ISSUE TITLE
Mounting fails: Could not find fusermount binary

### ISSUE THREAD

**Issue by saviola777** [oniony/TMSU#51]
Hello,

since the current stable release does not work for me, I wanted to confirm the error by compiling it myself before creating an issue for it. Unfortunately, I can't seem to get that to work either. While it compiles fine, it gives an error during the unit tests (and also when using ```tmsu mount```):

    go test github.com/oniony/TMSU/...
    ?       github.com/oniony/TMSU  [no test files]
    2015/10/21 09:26:34 Could not find fusermount binary: exec: "/bin/bin/fusermount": stat /bin/bin/fusermount: no such file or directory
    FAIL    github.com/oniony/TMSU/cli      0.016s

Output of ```whereis fusermount```:

    fusermount: /usr/bin/fusermount /usr/share/man/man1/fusermount.1.bz2

I believe that it is a problem with my system / environment or with Go (I have never worked with or compiled anything with Go before). ```printenv``` does not show anything pointing to ```/bin/bin```, though. Does Go use a different environment variable with a strange default value or something? The problem exists on both the master branch and the v0.5 branch. My apologies if this is not actually a TMSU error but an error on my system, feel free to close the issue if that is the case.

Thanks in advance.

Edit: ```go env``` output:

```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/saviola/gocode"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

```go version```: ```go version go1.4.2 linux/amd64```

**Comment by oniony** [comment]
Do you have FUSE installed? If not, there should be a package available in
your operating system's package manager, e.g apt-get, pacman, yum, &c.

**Comment by saviola777** [comment]
```eix sys-fs/fuse```:

```
[I] sys-fs/fuse
     Available versions:  2.9.3 2.9.4 {examples static-libs KERNEL="FreeBSD linux"}
     Installed versions:  2.9.4(02:40:38 PM 07/08/2015)(-examples -static-libs KERNEL="linux -FreeBSD")
     Homepage:            http://fuse.sourceforge.net
     Description:         An interface for filesystems implemented in userspace
```

There is another package called ```go-fuse```:

```
dev-libs/go-fuse
     Available versions:  ~0_p20140812-r1^s ~0_p20150422^s **9999^s
     Homepage:            https://github.com/hanwen/go-fuse
     Description:         native bindings for the FUSE kernel module
```

But I think I installed that as part of the TMSU Go dependencies, right? The main problem here seems to be that it looks for ```fusermount``` in ```/bin/bin```, a directory which does not exist.

**Comment by oniony** [comment]
Hi, sorry, yes, did not notice that as I was reading it on my phone. You are indeed correct in that looking wrong. I shall take a look a little later on today.

Thanks for reporting this issue.

**Comment by saviola777** [comment]
Thanks! I think I found the source of the problem, and it's an "upstream bug" in [this](https://github.com/hanwen/go-fuse/blob/c2130ac9e52cdd7ec9b819922fc9a8c5aba9d8dc/fuse/mount_linux.go#L138) file, it looks for "/bin/fusermount" in the PATH, which it can't find (I don't have "/usr" in my PATH). It was introduced only [recently](https://github.com/hanwen/go-fuse/commit/41b8187f5b1cd7af28a1a04cad50405c2dd5a5e9), and should be fixed if I use the latest stable version instead. I'll raise the issue in the go-fuse project and come back here to close this as soon as I have tested it with the stable version of go-fuse.

**Comment by oniony** [comment]
Great. Many thanks for investigating and letting me know.

**Comment by saviola777** [comment]
Okay, while there is no stable version of go-fuse, checking out an older state of the repo worked, TMSU compiles and passes the tests now.

**Comment by oniony** [comment]
Great, thanks.
