### ISSUE TITLE
tmsu repair --manual "$V" causes panic

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#56]
`tmsu repair --manual path/to/existing/file.txt`

```
panic: runtime error: index out of range

goroutine 1 [running]:
tmsu/cli.repairExec(0xc8200a23c0, 0x1, 0x1, 0xc8200665f0, 0x1, 0x1, 0xc82008a400, 0x14, 0x0, 0x0, ...)
	/home/kau/zba/vrici/tmsu/src/tmsu/cli/repair.go:78 +0x33d
tmsu/cli.Run()
	/home/kau/zba/vrici/tmsu/src/tmsu/cli/cli.go:58 +0x45a
main.main()
	/home/kau/zba/vrici/tmsu/src/tmsu/main.go:23 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
```

Found while attempting to get TMSU to recalculate the fingerprint of a file. I still haven't worked out how to do that. `tmsu repair --manual $V $V` appears to null out the fingerprint field (maybe that is a separate bug; the file still exists, is an ordinary file and not of zero size, so probably it shouldn't null the fingerprint). `tmsu repair $V` goes off across the DB, reporting all sorts of stuff, but doesn't recalculate the fingerprint. (and is otherwise unsuitable as it only works at all on a sufficiently small db)

**Comment by oniony** [comment]
Hi. Thanks for reporting this.

A manual repair requires two arguments: the 'from' and 'to' path, though it obviously shouldn't panic if you forget one.

As for recalculating fingerprints: there's an option to repair, `--unmodified`, that will force recalculation of fingerprints. If you only want to do it for a subset of the files then combine it with the `--path` option.

`repair --manual blah blah` shouldn't blat the the fingerprint, so that could be a bug too: I'll investigate.

**Comment by 0ion9** [comment]
> A manual repair requires two arguments: the 'from' and 'to' path, though it obviously shouldn't panic if you forget one.

Yes, I was aware of that. Once I exhaust what seem to me to be the smart options, I start going through the stupid ones just in case ;)

> As for recalculating fingerprints: there's an option to repair, --unmodified, that will force recalculation of fingerprints. If you only want to do it for a subset of the files then combine it with the --path option.

Ah, I had tried `--unmodified` with no success, didn't realize it needed to be combined with `--path`. I also did not realize, from what the help said (blurb + examples), that you could pass a *filename* (rather than a directory) to --path and it would work correctly.
I've filed that fact away in my mind and my shell-function library :)

**Comment by oniony** [comment]
>Ah, I had tried --unmodified with no success, didn't realize it needed to be combined with --path

It doesn't (shouldn't) *need* to be combined with `--path`, but the option there if you don't want to recalculate all of the fingerprints.

    tmsu repair --unmodified

Should recalculate **all** of the fingerprints. If it does not then that's (yet) another bug.
