### ISSUE TITLE
Is there a way to record the URL of a file?

### ISSUE THREAD

**Issue by eflyinghi** [oniony/TMSU#58]
Is that a way to record the URL of a file?

I wanted to record the original download site of a file.  But the value of a tag cannot contain \ and maybe other chars in a url.  So is it possible to set up a special tag (e.g. url=xxx) which allows these chars?

**Comment by eflyinghi** [comment]
After I created this request, I found it would be resolved by #45.
But I wanted to clarify that it's not possible to add some escape chars for a URL.  So maybe add an option instead of escape chars was a good method.

**Comment by 0ion9** [comment]
I'm running TMSU git (ie. the latest code) and `/` still isn't allowed in values.

That said, there are characters which TMSU does allow that are workable substitutes for /. Try running your URI through `sed 's,/,╱,g'`

**Comment by oniony** [comment]
I've had to prohibit slashes as they don't work in the FUSE virtual filesystem.

Options:

1. Continue to not allow these slash characters in TMSU.
2. Allow slashes but omit these entries from the virtual filesystem.
3. Substitute the slashes for another character sequence in VFS (effectively escape them).

The benefit of ① is that it's already implemented. The drawback of ② is that it's not terribly transparent as to why your tags/values are not appearing in the VFS. The drawback of ③ is that is that the escaped slashes will be quite ugly and the character used for escaping will, too, have to be escaped.

**Comment by oniony** [comment]
Regarding #45, as @0ion9 has pointed out, it does not address slashes in particular because of the VFS limitations.

**Comment by oniony** [comment]
So, of the above options, let's discount ① because that's no fun.

So between ② and ③, ③ seems more 'right' as it's transparent and directly works around the problem rather than giving up to it. So then I guess we need to come up with an agreeable solution to escaping these characters in the VFS.

@0ion9 has suggested using `╱` as a workaround to TMSU current limitations, which is fine on an individual basis, but I don't think this would be a good solution for TMSU itself as it's easily confused with a slash so again is not very transparent.

Options:

1. [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding), e.g. `http:%2F%2Ftmsu.org%2F`. This will mean any `%` will also be escaped, e.g. `100%` will become `100%25`.
2. [HTML/XML encoding](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references), e.g. `http:&#47;&#47;tmsu.org&#47;`. This will mean any `&` will also be escaped, e.g. `his & hers` will become `his &amp; hers`.
3. Custom, by using a stand-in character. The stand-in character would probably have to be in ASCII for it to work universally, plus it would have to be little used as it would, itself, need escaping. Possible candidates:
  * Tilde `~`, e.g. `~s` for `/`, `~b` for `\` and `~~` for `~`.
  * Dollar `$`, e.g. `$s` for `/`, `$b` for `\` and `$$` for `$`.
  * Percent `%`, e.g. `%s` for `/`, `%b` for `\` and `%%` for `%`.
  * Hash `#`, e.g. `#s` for `/`, `#b` for `\` and `##` for `#`.

**Comment by oniony** [comment]
(TIL It's really hard to escape backticks in Markdown.)

**Comment by eflyinghi** [comment]
But I like solution ② 
How about make a special tag, e.g. "Note". 
Note tag is a special tag which won't show in VFS, neither can filter by this tag, and justed used to save text (supports multiple lines if possible) in database.

From a user of view, after I added a file into the file management system (tmsu) and tagged it, I could attach a note to the file, such as a digest/summary/download URI and whatever I wanted to note.
E.g.  tmsu note /path/to/file "http://..."
And I could also use the command to show the note or change the note.

**Comment by oniony** [comment]
Hmm, I'll have a think about this idea for a new type of meta-data. I'm not too keen on the idea though as it would duplicate much of the functionality (and code) of tag values and only have this one special property.

Perhaps I'll look at option ② (omit from VFS) for now then as it's simple to do and gets you URLs in the simplest way possible.

**Comment by eflyinghi** [comment]
If supports VFS, could it be a parallel note file? 
For example, if a file/directory has a note, when it was show in VFS, there could show another file:
.../origin.file.or.dir
.../origin.file.or.dir.note

The xxx.note file is a txt file and it showes the note string if cat the .note file

**Comment by oniony** [comment]
If we go down that path, then yes, that could be an option. However I'm a bit reluctant to go down that path because of the added complexity. I'd rather try to build in support for slashes into the existing functionality.

**Comment by 0ion9** [comment]
:-1: on the idea of a separate type of tag. That is confusing from both a code and user perspective, in addition to creating a special case that doesn't actually seem special enough to warrant dedicating code to it.

(however, I note that if you ( @eflyinghi ) personally want to implement such a thing, TMSU does not change any other tables you add to the database, so it would be fairly easy to implement personally using `sqlite3` command (create a new table `notes` with three fields, (note_id,file_id.note_content)).)

So it should be clear that personally I'm in favor of ③.
I think $ is an obvious no (confusing vs $shell_variable expansion), For URIs, `#` seems like a good choice. as # normally can only occur once in a valid URI. `#` is also less odd-looking than all other options, IMO.

**Comment by eflyinghi** [comment]
@0ion9 ,I don't think any of escape char was good at this place.  Because once you get the URI, you maybe want to download/paste/share...and then you have to change it back.  

And per issue #45, I think there must be other users want to make a clear text note for a file~.
So if there's an ability to add a note/digest/summay/comment to the tagged files would be valued.

**Comment by 0ion9** [comment]
@eflyinghi :
Of course you have to change it back. That's what scripting is for; if you set it up sensibly, there should be no need for you to know the value is escaped, except if you need to interact with the VFS.

**Comment by eflyinghi** [comment]
@0ion9, Well, 2) and 3) both could work for me.  And as you suggested, I could add database persionally. But from my (the real user) point of view, I perfer to 2), because I don't need the URI show in VFS, I just wanted to make a note to the file.  

And beside URI, maybe I would write other notes.  Don't need show in VFS too I think.  Instead, the note need to support multiple lines.  So it's not a tag, maybe I'm requesting another feature than tag. :smile: More like "Readme", I could put URI/Author/Contact/Serial Number, etc to the note. :smiley_cat:

**Comment by 0ion9** [comment]
@eflyinghi : what you don't seem to understand is that **from the user's point of view, there is no escaping**, except when they are using the VFS.

It is possible that Paul might implement it differently, but currently, there doesn't seem any good reason to me why the escaping would need to be shown to the user outside of VFS, and so far he's been very thoughtful in minimizing the amount of escaping shown to the user.

**Comment by eflyinghi** [comment]
I'm sorry @0ion9 , maybe I don't understand escaping, neither understand what's your meanings.  Nor to VFS, I didn't use tmsu/vfs for a while.  I'm just searching a tool for management files. 

I'm not English mother tongue, so there might be some mis-understandings.

So I just state what I want:  A tag based file system, with duplicated files detecting.
Then I found that TMSU is just the tool I'm searching for, except it cannot make a note/comment/URL for a file.  

At first, I considered how to work-around with valued tag for note/url.  So I opened this issue. :smile: 
But later, I realized that the note may be complex and multi-line, so my request becomes a new feature.

Sorry for bother you and warm wishes at Thanksgiving. :gift:

**Comment by oniony** [comment]
Guys,

Seems to be a bit of confusion.

What we'll do is ② for now as it's quick and easy and, although I don't like it because it's not transparent to the user, it'll be fine for the short term. That'll get you, @eflyinghi, able to store URLs and we can then worry ③, escaping, later.

VFS is the virtual filesystem. When you run `tmsu mount` to mount the database as a virtual directory. The problem is slashes can't exist in filenames because they're used for path separators. So we'll need to escape them: basically use something else in their place. As @0ion9  has pointed out, this will affect nothing *except* the virtual filesystem, as TMSU can spit out the slashes fine when run from the command-line (although it has implications for piping, but we'll think about that later when we do ③).

So 0.7.0 will release with ③ complete (unless there are obstacles) but I'll check in a ② solution in the interim.

Hopefully this is all clear and argeable to everyone.

**Comment by 0ion9** [comment]
@eflyinghi : I see, I hadn't noticed the problem of multiline tag values. My impression overall is not that you didn't understand escaping, but rather that you didn't understand that VFS was a completely optional aspect of TMSU. So when we were discussing escaping schemes, I think you took that as something that affected the whole of TMSU.

@oniony  AFAICS, this is indeed a current "deficiency", it seems you cannot use newlines inside tag values. The error message is kind of funny:

```
$ cd /tmp
$ tmsu init
$ N=$'\n'
$ touch foo
$ tmsu tag foo bar=foo-${N}bar
tmsu: new tag 'bar'
tmsu: tag value cannot contain '
'
```

(ditto for tab, whether escaped -- `T=$'\t'; tmsu tag foo bar=foo-'\'${T}bar`) -- or not.)
Obviously if \n and \t were allowed they'd have to be escaped in `tmsu tags` output or it would be horribly ambiguous.

Implications for piping? Piping is already a bit breakable imo:

```
$ touch 'bad: touch'
$ tmsu tag 'bad: touch' 'foo:\ bar'
# okay
$ tmsu files 'foo:\ bar'           
./bad: touch
# Correct parsing splits on ': ', takes the last arg as the list of tags,
# joins the remainder with ': ''s, and takes that as the filename.
#
# or in shell terms, FN=${V%: *};TAGS=${V#$FN: }
# but that's just off the top of my head and not tested.
$ tmsu tags 'bad: touch' foo
bad: touch: foo foo:\ bar
foo:

```

(not that it tends to break in actual usage. But a ': ' is not that unlikely in a filename, for example a saved webpage might contain that string.)

**Comment by oniony** [comment]
>it seems you cannot use newlines inside tag values

Ha. Newlines hadn't even crossed my mind. I'll have to take a look at these non-obvious characters.

I'll have to revisit escaping. I spent so much time on it recently that I parked it for a while as it was turning my brain to mush. The Zsh completion is especially painful: I just couldn't get the variable substitution to handle whitespace, so you can't tab complete these at the moment.

**Comment by oniony** [comment]
@eflyinghi You should now be able to use slashes within tag or value names, as per interim solution ②.

For your purposes it'd probably make most sense to stick to values:

    tmsu tag somefile url=http://tmsu.org/

Let me know if there are any problems.

**Comment by eflyinghi** [comment]
exhilarating!  Thanks in advance. @oniony  I'll have a try :)

**Comment by oniony** [comment]
Sorry it's taken me so long to fix this up: been very busy with work and life of late.

Anyhow, I've managed to implement this at the VFS level now by substituting slashes with doppelgangers from Unicode. I'm not 100% happy with this approach as it if you don't have completion then realising what is going on is nigh on impossible. However it does mean that we can now have the these tags/values actually showing up.

The surrogate characters are the mathematical operators [U+2215](http://www.fileformat.info/info/unicode/char/2215/index.htm "Division slash") and [U+2215](http://www.fileformat.info/info/unicode/char/2216/index.htm "Set minus"). Just in case anyone happens to want tags with these particular obscure characters in them, I'm actually also inserting a zero-width space [U+200B](http://www.fileformat.info/info/unicode/char/200B/index.htm "Zero width space") as an escape character before the surrogates. As this character is not allowed in tag/value names, is not necessary for me to escape the presence of any of those!

So, to illustrate this, a tag name of 'http://example.com/' will be appear in the VFS as 'http:[U+200B][U+2215]example.com[U+200B][U+2215]'.

(The Zsh completion still needs some love.)

**Comment by 0ion9** [comment]
> The surrogate characters are the mathematical operators U+2215 and U+2215.

2215 and 2215? Hm.. I'm guessing the second was supposed to be U+2216 "∖"

Really good to hear this is working now;Pretty important to be able to accommodate urls or paths IMO.

**Comment by oniony** [comment]
Yes, I meant 2215 and 2216 :/

**Comment by oniony** [comment]
OK, Zsh completion seems to be working now, I'm going to call this done. Please reopen if there are any issues I've not spotted.
