### ISSUE TITLE
Cannot open mounted directories of unused tags

### ISSUE THREAD

**Issue by gcavallo** [oniony/TMSU#60]
I'm having an issue similar to #29 with 0.6.0 when opening an empty tag folder. If I create a tag without tagging any files to it, opening it's folder with ls or thunar/nautilus will fail:

    ~$ tmsu mount ~/TMSU
    ~$ mkdir TMSU/tags/Empty
    ~$ ls TMSU/tags/Empty/
    ls: cannot open directory 'TMSU/tags/Empty/': Software caused connection abort
    ~$ ls TMSU/tags
    ls: cannot access 'TMSU/tags': Transport endpoint is not connected

The only way I've found to fix this is by unmounting with `fusermount -uz` and delete the tag with tmsu (deleting the mounted folder with rm will fail).

So far only empty directories are causing this issue, browsing tags with files does work fine.

**Comment by oniony** [comment]
Thanks for reporting. I'l try to have a look at this tomorrow morning on my commute.

**Comment by oniony** [comment]
Hi, this issue should be fixed now, sorry about that.

**Comment by oniony** [comment]
Actually, I've decided to release a 0.6.1 with this fix in. Will probably be a few days until it's ready though.

**Comment by gcavallo** [comment]
Thanks for the fix. I discovered TMSU just recently and I'm loving it!  :thumbsup:

**Comment by oniony** [comment]
Glad to hear you're enjoying it. Let me know if you have any suggestions or
critique.

**Comment by oniony** [comment]
Version v0.6.1 published.
