### ISSUE TITLE
Drilling down into multiple values on same tag without queries

### ISSUE THREAD

**Issue by hbaughman** [oniony/TMSU#70]
I would very much like to use TMSU to manage my movie collection in conjunction with [Kodi](https://kodi.tv/), a media manager with a 10' interface designed for use with a TV remote. I'd love to use TMSU for this because that would let my organization scheme for management _directly mirror_ the scheme for consumption.

When using my CLI I can easily search for the intersection of multiple of the same tag by either:

```
`ls tags/actor/=bogart/actor/=bergman`
```

Unfortunately when using a file manager, in the first case, the `actor` tag does not _appear_ in `tags/actor/=bogart`. This prevents me from being able to navigate to this path using a TV remote and Kodi. I'd really prefer to keep the directory tree uncluttered and not simply namespace my tags (e.g., `tags/actor_bogart/actor_bergman`).

Is there a way to enable the display of a tag (`actor`) inside a path that already uses this tag (`tags/actor/=bogart`)?

**Comment by oniony** [comment]
Firstly thanks for reporting this. Yes, that appears to be a bit of an oversight on my part. I'll look to fixing this.

**Comment by oniony** [comment]
I've done this by simply showing tags again at every level, even if they're already on the path. This is a naive solution. The better solution would be to not repeat tags if they don't actually have any values.

**Comment by oniony** [comment]
I've improved this to only relist tags that actually have values. The actual values themselves will also be relisted as I haven't made the effort to filter out the ones already used as it's a bit more fiddly.
