### ISSUE TITLE
Help command doesn't list the version command

### ISSUE THREAD

**Issue by fturco** [oniony/TMSU#77]
According to tmsu(1) there are 21 commands, from `config` to `version`. According to `tmsu help` there are only 20 commands because the last one, `version`, is missing. This should be trivial to fix. I'm running tmsu 0.6.1 on a Parabola GNU/Linux-libre system.

**Comment by oniony** [comment]
I think I hid the version and vfs commands to simplify the list. They
appear if you do --verbose/-v. You can get version info also with the -V
option.
