### ISSUE TITLE
Accept both spelling of color/colour

### ISSUE THREAD

**Issue by fturco** [oniony/TMSU#81]
The tmsu(1) man page describes the `--colour` option (UK spelling), while the `tmsu help` command describes the `--color` option (US spelling). But I get the following error message:

```
$ tmsu --colour=always tags *.pdf
tmsu: invalid option '--colour'
```

It would be nice for TMSU to accept and describe both spelling versions.

**Comment by oniony** [comment]
Hi, thanks for reporting this.

The spelling in the man page is a typo, it should be the US spelling '--color', as the precedent is already present in other tools for US spellings.

I could expand the tool to support option aliases and add the UK spelling but it's pretty low priority and bear in mind that 'ls' does not do this.
