### ISSUE TITLE
Make uninstall leaves tmsu-fs binaries on the filesystem

### ISSUE THREAD

**Issue by fturco** [oniony/TMSU#84]
When uninstalling TMSU with `make uninstall` the following binaries are left on the filesystem:

```
/usr/bin/tmsu-fs-merge
/usr/bin/tmsu-fs-mv
/usr/bin/tmsu-fs-rm
```

It should remove them too.

**Comment by oniony** [comment]
Thanks for reporting this. I'll update the makefile to gets these deleted.
