### ISSUE TITLE
Tag names containing : are not completed correctly

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#85]
First do some prep:

```
cd /tmp
tmsu init
echo text > file.txt
tmsu tag file.txt foo: bar: baz:bar :fabbar
# just for extra fun:
tmsu tag file.txt :
```

Then:
1. `tmsu (files|merge|rename|delete|..) <TAB>`
2. Take especial note of what the help looks like when you press Tab.

It looks like Zsh is consuming it (turning baz:bar into an item 'baz' with help 'bar', for example, and foo:, bar: both into items foo,bar with empty strings as help.)

Apparently colons need to be escaped via `\`.

EDIT: tag names are affected, but not values. `foo=bar:baz` completes correctly, for example. That includes contexts with a bare value only, like `tmsu delete --value`, too.

**Comment by oniony** [comment]
Thanks. I'll take a look. I had a lot of problems getting Zsh to play ball with colons correctly.

**Comment by 0ion9** [comment]
A quick attempt to fix that *seems* to work:

```
diff --git a/misc/zsh/_tmsu b/misc/zsh/_tmsu
index ddb7284..e1909df 100644
--- a/misc/zsh/_tmsu
+++ b/misc/zsh/_tmsu
@@ -72,7 +72,7 @@ _tmsu_tags() {
     _call_program tmsu tmsu $db tags | \
     while read tag
     do
-        local escapedTag=$tag:gs/:/\:/:gs/=/\\\\=/
+        local escapedTag=$tag:gs/:/\\\:/:gs/=/\\\\=
         tag_list+=("$escapedTag")
     done
 
@@ -198,7 +198,7 @@ _tmsu_query() {
         _call_program tmsu tmsu $db tags | \
         while read tag
         do
-            local escapedTag=$tag:gs/:/\:/
+            local escapedTag=$tag:gs/:/\\\:/
             escapedTag=${escapedTag:gs/=/\\\\&}
             escapedTag=${escapedTag:gs/!/\\\\&}
             escapedTag=${escapedTag:gs/</\\\\&}
```

I've tested it successfully with the above cases.

Then I dug up a few cases which fail:

`tmsu tag file.txt '::::::::::\\::aaaaah' '::::::::::\\=:noo' '::::::::::\=:what'`

1. the backslash escape is not properly escaped, so `tmsu files ::::::::::<TAB>` completes with a missing \ character, resulting in `tmsu: no such tag '::::::::::::::::::::::aaaaah'`
2. Generally disappears from the completion list. If you enter `tmsu files ::::::::::\=<TAB>` , it will be completed, without escaping, resulting in `tmsu: no such tag '::::::::::'`
3.  This case does not fail, it can be correctly entered via `tmsu files ::::::::::\\<TAB>` or similar. Included for contrast with case 2.

**Comment by xelxebar** [comment]
@0ion9 Nice! Tested your patch on my machine and it works like a charm. Though I didn't futz with the pathological cases you looked at.

Not sure if it's relevant, but there are a couple other `escapedTag` and `escapedValue` lines that you didn't touch but look really similar. In particular, the two middle blocks in the patch below:

    diff --git a/misc/zsh/_tmsu b/misc/zsh/_tmsu
    index ddb7284..818c1c1 100644
    --- a/misc/zsh/_tmsu
    +++ b/misc/zsh/_tmsu
    @@ -72,7 +72,7 @@ _tmsu_tags() {
         _call_program tmsu tmsu $db tags | \
         while read tag
         do
    -        local escapedTag=$tag:gs/:/\:/:gs/=/\\\\=/
    +        local escapedTag=$tag:gs/:/\\\:/:gs/=/\\\\=/
             tag_list+=("$escapedTag")
         done
     
    @@ -166,7 +166,7 @@ _tmsu_query() {
             local line
     
             local tag=$words[$#words-2]
    -        local escapedTag=$tag:gs/:/\:/
    +        local escapedTag=$tag:gs/:/\\\:/
             escapedTag=${escapedTag:gs/=/\\\\&}
             escapedTag=${escapedTag:gs/!/\\\\&}
             escapedTag=${escapedTag:gs/</\\\\&}
    @@ -178,7 +178,7 @@ _tmsu_query() {
             _call_program tmsu tmsu $db values "$tag" | \
             while read value
             do
    -            local escapedValue=$value:gs/:/\:/
    +            local escapedValue=$value:gs/:/\\\:/
                 escapedValue=${escapedValue:gs/=/\\\\&}
                 escapedValue=${escapedValue:gs/!/\\\\&}
                 escapedValue=${escapedValue:gs/</\\\\&}
    @@ -198,7 +198,7 @@ _tmsu_query() {
             _call_program tmsu tmsu $db tags | \
             while read tag
             do
    -            local escapedTag=$tag:gs/:/\:/
    +            local escapedTag=$tag:gs/:/\\\:/
                 escapedTag=${escapedTag:gs/=/\\\\&}
                 escapedTag=${escapedTag:gs/!/\\\\&}
                 escapedTag=${escapedTag:gs/</\\\\&}
