### ISSUE TITLE
Provide some way to get a full list of all unique tag=value pairs

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#93]
Just recently, and several times in the past, I've encountered this scenario, where I can see a particular value in `tmsu values` and want to find out the tag(s) using it. (ie. the exact inverse of `tmsu values TAGNAME` -- notionally, `tmsu tags --value VALUENAME`)

Of course this is possible using sqlite3 CLI:

```
DB=$(tmsu stats | head -1 | cut -d ' ' -f 2-)
sqlite3 "$DB" -separator $'t' '
  select T.name, V.name from 
      (select distinct tag_id, value_id from file_tag where value_id != 0) as U
          join tag as T on U.tag_id=T.id join value as V on U.value_id=V.id;'
```

(..and then piping that into grep...)

But it seems reasonable that TMSU should provide this particular function. It's frankly a lot more useful for managing cleanups than a plain list of values, or values-for-a-given-tag.

**Comment by oniony** [comment]
Yes, definitely agree that would be useful. I'll see what I can do.

**Comment by oniony** [comment]
>`tmsu tags --value VALUENAME`

This suggestion is pretty much perfect for this.

**Comment by oniony** [comment]
I've added the `--value` option to the `tags` subcommand. However, it currently does not consider implied values, e.g. if you have an implication of `huge` to `size=big`, listing the tags for `big` will show only `size` at this time.

**Comment by 0ion9** [comment]
Looks good, I'll have to work up something that uses it specifically to find marginal T/V pairs. Just tested it, spotted a small bug: `tmsu tags -v big` is interpreted as if it were `tmsu --verbose tags big`, rather than `tmsu tags --value big`. `tmsu tags --value big` works as expected.

**Comment by oniony** [comment]
Aha, thanks, I'll change the flag.

**Comment by oniony** [comment]
I'm going to call this closed for now. I deliberated about showing tags for values used via implications, but it just doesn't feel right: it's not the same as showing tags used by files. I might come back to this.
