### ISSUE TITLE
How do you merge a database to another?

### ISSUE THREAD

**Issue by manishrjain** [oniony/TMSU#94]
I have two directories:

dirA owns dirB. Both have their own tmsu dbs. I want to merge dirB's tmsu db with dirA's tmsu db, and then delete dirB's version. Essentially a merge-move sort of thing. How would you do that with current tools?

**Comment by oniony** [comment]
Firstly take backups of your two databases.

Then, you'd need to manually get the data from database B into database A.
You could do that by exporting it using the Sqlite tooling and then
inserting it into database A by running the export script into database A,
though you'd need to first update the identifiers so they don't clash with
the existing ones and make sure you don't have any tag name clashes.

Finally you'd need to run a 'tmsu repair' to fix the paths.

It's a bit fiddly to be honest.

**Comment by oniony** [comment]
Not an issue; closing.
